NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 100
MODEL:
  TRANSFER_TYPE: "prompt"
  TYPE: "prompted-dit"
  DEPTH: 23
  LINEAR:
    MLP_SIZES: []
  FEATURES_LAYER_LIST: [14, 18, 24]
  
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "adamw"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 100
  WARMUP_EPOCH: 10
  TOTAL_EPOCH: 100
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "sup_vitb16_224"
  BATCH_SIZE: 128
